apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.container_image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.APP_PORT }}
        volumeMounts:
            - name: {{ .Release.Name }}-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      volumes:
      - name: {{ .Release.Name }}-volume
        configMap:
          name: {{ .Release.Name }}-configmap
          items:
            - key: default.conf
              path: default.conf
      imagePullSecrets:
      - name: {{ .Values.image_pull_secrets_name }}